# Generated by Django 5.1 on 2024-08-21 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1234567890'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10}$')]),
        ),
    ]
